# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# NOTE: this action sets up the Java toolchain + Gradle with caching,
#       it is a convenience wrapper, so that we can use it in all workflows.

name: setup-java-with-cache
description: Setup Java toolchain and Gradle with caching
inputs:
  java-version:
    description: "Java version to use"
    required: false
    default: "17"
  java-distribution:
    description: "Java distribution to use"
    required: false
    default: "temurin"
  gradle-version:
    description: "Gradle version to use"
    required: false
    default: "9.2.1"
  gradle-cache-disabled:
    description: "Whether to disable Gradle caching"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Java (with cache)
      if: inputs.gradle-cache-disabled != 'true'
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: gradle

    - name: Setup Java (no cache)
      if: inputs.gradle-cache-disabled == 'true'
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: ${{ inputs.gradle-version }}
        cache-disabled: ${{ inputs.gradle-cache-disabled }}

    - name: Verify Java installation
      run: |
        echo "Java setup complete"
        java --version
        gradle --version
      shell: bash
