# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Bug Report
description: Report a bug in Apache Iggy
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What happened? What did you expect to happen instead?
      placeholder: |
        Describe the bug clearly. Include:
        - What you were doing
        - What you expected
        - What actually happened
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment
      description: How is Iggy server deployed?
      options:
        - Docker (DockerHub image)
        - Docker (self-built image)
        - Compiled from source
        - Pre-built binary / release artifact
        - Not applicable
    validations:
      required: false

  - type: input
    id: versions
    attributes:
      label: Versions
      description: Iggy server and SDK versions. A git tag, commit SHA, DockerHub tag, or package manager version (crates.io, Maven, NuGet, npm, PyPI) is also acceptable.
      placeholder: "e.g., server 0.6.3, Rust SDK 0.8.3, Node.js SDK 0.6.3, Java SDK 0.6.3, Python SDK 0.6.4"
    validations:
      required: false

  - type: input
    id: hardware
    attributes:
      label: Hardware / environment
      description: Where is this running and what storage is used?
      placeholder: "e.g., AWS EC2 c5.xlarge with EBS gp3, local PC with NVMe, GCP n2-standard-4 with ephemeral SSD"
    validations:
      required: false

  - type: textarea
    id: sample-code
    attributes:
      label: Sample code
      description: Producer/consumer initialization and message loop (if applicable).
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Relevant logs from the SDK or Iggy server. Server writes to stdout and to `local_data/logs/iggy-server*`. You can also attach the output of `iggy snapshot`.
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Iggy server config
      description: |
        Your `config.toml` overrides, `local_data/current_config.toml` (generated by the server on startup with resolved values), or custom `IGGY_*` environment variables.
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Steps to trigger the bug and/or a minimal reproducible project (repo link or inline script).
      placeholder: |
        1. Start the server with ...
        2. Send messages using ...
        3. Observe ...
    validations:
      required: false
