# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: ci-publish-go
on:
  push:
    tags:
      - "foreign/go/v*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        id: extract
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Validate tag format
        run: |
          if [[ ! "$TAG" =~ ^foreign/go/v([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$ ]]; then
            echo "Tag $TAG does not match required format: foreign/go/vX.Y.Z"
            exit 1
          fi
          echo "Valid Go module tag: $TAG"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check go.mod module path in foreign/go
        run: |
          MOD_PATH=$(grep '^module ' foreign/go/go.mod | awk '{print $2}')
          if [[ "$MOD_PATH" != "github.com/${{ github.repository }}/foreign/go" ]]; then
            echo "go.mod module path ($MOD_PATH) does not match expected path: github.com/${{ github.repository }}/foreign/go"
            exit 1
          fi
          echo "go.mod module path is correct: $MOD_PATH"

      - name: Check if go.mod version matches tag
        run: |
          TAG_VERSION="${TAG#foreign/go/}"
          # Check if go.mod contains this version in replace or require (not strictly necessary, but can be used for extra checks)
          echo "Tag version is $TAG_VERSION (no strict version field in go.mod to check for single module)"
          # (No error here, just informative)

      - name: Run go mod tidy
        working-directory: foreign/go
        run: |
          go mod tidy
          git diff --exit-code || (echo 'Please run "go mod tidy" and commit the changes before tagging.' && exit 1)

      - name: Run Go tests
        working-directory: foreign/go
        run: go test -v ./...

